In [1]:
import numpy as np

from DenseLayer import DenseLayer
from ActivationFunc import Softmax
from LossFunc import CategoricalCrossEntropy

X = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[1, 0, 0], [0, 1, 0]])

X

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
dense = DenseLayer(3, 3, Softmax)

dense.forward(X)

dense.output

array([[0.34604462, 0.32507486, 0.32888052],
       [0.36417427, 0.30911306, 0.32671267]])

In [3]:
y

array([[1, 0, 0],
       [0, 1, 0]])

In [4]:
loss = CategoricalCrossEntropy().calculate(y, dense.output)

loss

(array([1.06118755, 1.17404819]), np.float64(1.1176178726665595))

In [5]:
from Accuracy import Accuracy
acc_metric = Accuracy("categorical")
acc_metric.calculate(y, dense.output)

np.float64(0.5)