In [1]:
import numpy as np

from DenseLayer import DenseLayer
from ActivationFunc import Softmax
from LossFunc import CategoricalCrossEntropy

X = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[1, 0, 0], [0, 1, 0]])

X

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
dense = DenseLayer(3, 3, Softmax)

dense.forward(X)

dense.output

array([[0.3122873 , 0.33614227, 0.35157043],
       [0.28075797, 0.33913938, 0.38010265]])

In [3]:
y

array([[1, 0, 0],
       [0, 1, 0]])

In [11]:
loss = CategoricalCrossEntropy().forward(y, dense.output)

loss

(array([1.16383168, 1.08134411]), np.float64(1.122587896006621))

In [20]:
from Accuracy import Accuracy
acc_metric = Accuracy("categorical")
acc_metric.forward(np.array([[0, 0, 1], [0, 1, 0]]), dense.output)

np.float64(0.5)